server:
  port: 8203

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-product?useUnicode=true&serverTimezone=GMT&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  endpoint: ${ALIYUN_ENDPOINT}
  keyid: ${ALIYUN_KEYID}
  keysecret: ${ALIYUN_KEYSECRET}
  bucketname: ${ALIYUN_BUCKETNAME}
